### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by kruedae** [joaquinbarroso/UVeh-Vis#3]
I installed the repository as specified in the readme file and UVeh-Vis -h works fine. However, I'm trying to use
UVeh-Vis -wl 250,700 [-dev 0.4] output_SP.out
but I get:
File not found. Please enter a valid filename.
I tried with the full path and copying the file in the folder that has UVeh-Vis, but nothing seems to work. Any suggestion or example?

**Comment by EmanuelContC** [comment]
Output from `UVeh-Vis -h` stablishes the -dev option bewteen brackets as a sing that thisbparameter is not mandatory, when you want to use it, it has to be without them, so the line should be: 
`UVeh-Vis -wl 250,700 -dev 0.4 output_SP.out`

**Comment by kruedae** [comment]
Problem solved, thank you!
